language: node_js
node_js:
- '6.1'
- '5.11'
- '4.4'
- '0.12'
before_script:
- "npm install -g codeclimate-test-reporter"
script: "npm run coverage"
addons:
  code_climate:
    repo_token: b597676ee62c80768dad22866566e4bb0886ab6f4fd7f49f18cdfffa870347b0
after_script:
- codeclimate-test-reporter < coverage/lcov.info
